#! /usr/bin/tcsh -f
#
# replacer
#

#echo shlaom

if ($#argv < 3) then
  echo "Usage: replacer [in-str] [out-str] file-name"
  exit(1)
endif

setenv SREPLACER ~/bin/sreplacer
setenv TDIR /tmp/sariel/replacer

#echo $TDIR
mkdir -p $TDIR

setenv TFILE $TDIR/patterns.txt
#echo $TFILE
#exit

echo "-$1" > $TFILE
echo "+$2" >> $TFILE
echo ""    >> $TFILE
#echo bogi
#exit 

foreach FILENAME ($argv[3-]) 
    if  ( "$FILENAME:e" == "old" ) then
        continue;
    endif
    if  ( -d $FILENAME ) then
        echo "["$FILENAME"]" is a directory!
        continue;
    endif
    $SREPLACER $TFILE < $FILENAME > $FILENAME.x 
    mv $FILENAME $FILENAME.old
    mv $FILENAME.x $FILENAME
end

cmp -s $FILENAME $FILENAME.old
if  ( $status == 0 ) then
#    echo equal
    rm $FILENAME.old >& /dev/null
else
#    echo different
endif


