#! /bin/bash

function  handle_file() {
    if [[ -d $1 ]]; then
        continue
    fi

    MIDFILE="logs_final/"$(realpath  --relative-to=logs/ $1)
    DIR=$(dirname $MIDFILE);
    
    echo $MIDFILE
    echo $DIR
    mkdir -p $DIR >& /dev/null
    
    FLO=$MIDFILE
    if  [[ $1  -nt $MIDFILE ]]; then
        FLO=$(scripts/compress $1  | awk '{print $4}')
    fi


    if  [[ "$FLO" != "$MIDFILE" ]]; then
        echo "Error: Different files? $FLO != $MIDFILE"
        exit
    fi

    scripts/analyze_inner $FLO
}

for var in "$@"
do
    echo "$var"
    handle_file "$var"
done
