#! /bin/bash

function  handle_file() {
    FLO=$(scripts/compress $1  | awk '{print $4}')

    echo ""
    echo "FLO : " $FLO
    echo ""

    scripts/analyze_inner $FLO
}

for var in "$@"
do
    echo "$var"
    handle_file "$var"
done

