#! /bin/bash

if  [[ $# == 0 ]]; then
    echo "compress [LOG FILE]"
    exit -1
fi


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#echo $SCRIPT_DIR

function  handle_file() {
    if  [[ ! -e $1 ]]; then
        echo "Error: Unable to read file: " $1
        exit -1
    fi

    FOUT="logs_final/"$(realpath  --relative-to=logs/ $1)
    FDIR=$(dirname $FOUT );

    FOUTA=$FOUT".bak"

    mkdir -p $FDIR >& /dev/null

    grep -e "^#" -e "RUNTIME" $1 > $FOUT

    #echo "Out directory : " $FDIR

    replacer "# RUNTIME" "RUNTIME" $FOUT
    grep -v "## Task created:" $FOUT  > $FOUTA
    grep -v "## SEED"          $FOUTA > $FOUT
    grep -v -i "# START TIME:" $FOUT  > $FOUTA
    grep -v -i "# END   TIME:" $FOUTA > $FOUT
    grep -v -i "######################################################" \
                               $FOUT  > $FOUTA
#    mv $FOUT $FOUTA
    grep -v pmpl_script        $FOUTA > $FOUT

    rm $FOUTA >& /dev/null

    julia_fast julia/remove_all_dup_comments.jl $FOUT

    echo "Out filename  : " $FOUT
}

for var in "$@"
do
    handle_file "$var"
done

