#! /bin/bash

rm -r -f work >& /dev/null
mkdir work

#
# -a: pause/resume version
# 


START=$(date +%s)


### Without the -a it is the old version

# Wide search pause/resume version
./catalyst -a wait_random_busy/wrb_script work/


END=$(date +%s)

DIFF=$(( $END - $START ))

echo RUNTIME: $DIFF


exit

# Regular counter search abort/restart version
./catalyst wait_random_busy/wrb_script work/

# Wide search pause/resume version
./catalyst -a wait_random_busy/wrb_script work/

exit



exit




exit

# Script version
./catalyst -a wait_random/wait_random_script work/
