#! /bin/bash

function  do_a_run() {
    echo "Running (might take a while)..."
    #rm -r -f work >& /dev/null
    #mkdir work

    START=$(date +%s)

    echo ./catalyst $CATALYST_FLAGS $PROG work/

    ./catalyst $CATALYST_FLAGS $PROG work/ >> $LOG

    END=$(date +%s)

    DIFF=$(( $END - $START ))

    echo RUNTIME: $DIFF 
    echo "" >> $LOG
    echo "---------------------------------------------------" >> $LOG
    echo RUNTIME: $DIFF >> $LOG
    echo "" >> $LOG
    echo "" >> $LOG
    echo "" >> $LOG
}

############################################################

PROG=wait_random_busy/wrb_script

### Number of runs
TIMES=2

############################################################

LOG=log_wide_search.txt
CATALYST_FLAGS="-a"
rm -f $LOG
for i in  $(seq 1 $TIMES); do
    echo "LOG file: " $LOG
    echo "Wide search: " $i
    do_a_run
done

################################################################
LOG=log_parallel_search.txt
CATALYST_FLAGS="-p"
rm -f $LOG
for i in $(seq 1 $TIMES); do
    echo "LOG file: " $LOG
    echo "Wide search: " $i
    do_a_run
done


################################################################
LOG=log_counter_search.txt
CATALYST_FLAGS=""
rm -f $LOG
for i in $(seq 1 $TIMES); do
    echo "LOG file: " $LOG
    echo "Wide search: " $i
    do_a_run
done

echo BOGI

exit -1
